{
 "title": "Open Liberty (mpFaultTolerance-3.x)",
 "description": "Displays metrics collected by methods annotated with MicroProfile Fault Tolerance annotations",
 "tags": [ "microprofile" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "base_ft_invocations_total" },
   { "name": "avg_period", "label": "Moving Average", "query": "30s, 1m, 3m, 5m, 10m" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.98, 0.99, 0.999"
   },
   { "name": "topK", "label": "Top K values", "query": "3,5,10" }
  ]
 },
 "panels": [
  { "title": "Basic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fallbacks [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with @Fallback) which resulted in the fallback method or handler being called over the past $avg_period.\n\nIf no methods are annotated with @Fallback \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (result, fallback)(increase(base_ft_invocations_total{instance=~`${instance}`, fallback='applied'}[$avg_period]))*100/\nsum without (result, fallback)(increase(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Retries [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with @Retry) which resulted in a retry over the past $avg_period.\n\nIf no methods are annotated with @Retry \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (retryResult, retried)(increase(base_ft_retry_calls_total{instance=~`${instance}`, retried='true'}[$avg_period]))*100/\nsum without (retryResult, retried)(increase(base_ft_retry_calls_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Timeouts [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with @Timeout) which resulted in a Timeout over the past $avg_period.\n\nIf no methods are annotated with @Timeout \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (timedOut)(increase(base_ft_timeout_calls_total{instance=~`${instance}`, timedOut='true'}[$avg_period]))*100/\nsum without (timedOut)(increase(base_ft_timeout_calls_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Bulkhead Rejections [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with @Bulkhead) which were rejected because the bulkhead was full over the last $avg_period.\n\nIf no methods are annotated with @Bulkhead \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (bulkheadResult)(increase(base_ft_bulkhead_calls_total{instance=~`${instance}`, bulkheadResult='rejected'}[$avg_period]))*100/\nsum without (bulkheadResult)(increase(base_ft_bulkhead_calls_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Circuit Breaker Rejects [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with @CircuitBreaker) which were rejected because the Circuit Breaker was open over the last $avg_period.\n\nIf no methods are annotated with @CircuitBreaker \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (circuitBreakerResult)(increase(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult='circuitBreakerOpen'}[$avg_period])*100)\n/\nsum without (circuitBreakerResult)(increase(base_ft_circuitbreaker_calls_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Top $topK Most frequently failing methods over the last $avg_period",
   "type": "table",
   "description": "Percentage of calls which resulted in a failure.\n\nThis graph is showing failures after all fault tolerance processing has taken place (including fallback)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(${topK}, \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, result='exceptionThrown'}[$avg_period])) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period])) \n) \n> 0 "
    }
   ]
  },
  {
   "title": "Method invocations [per second, avg $avg_period]",
   "type": "graph",
   "description": "Number of method invocations which occurred per second for methods",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "repeat": "method",
   "yaxes": [
    { "format": "short", "label": "Invocations per second" }
   ],
   "targets": [
    {
     "expr": "sum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Method invocations averaged over $instance instance(s)  [per second, avg $avg_period]",
   "type": "graph",
   "description": "Number of method invocations which occurred per second for methods",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Invocations per second" }
   ],
   "targets": [
    {
     "expr": "sum by (method)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "method: {{method}}"
    }
   ]
  },
  {
   "title": "Failure rate [%, avg $avg_period]",
   "type": "graph",
   "description": "Percentage of calls which resulted in a failure.\n\nThis graph is showing failures after all fault tolerance processing has taken place (including fallback)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, result='exceptionThrown'}[$avg_period])) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Failure rate averaged over $instance instance(s) [%, avg $avg_period]",
   "type": "graph",
   "description": "Percentage of calls which resulted in a failure.\n\nThis graph is showing failures after all fault tolerance processing has taken place (including fallback)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (method)(rate(base_ft_invocations_total{instance=~`${instance}`, result='exceptionThrown'}[$avg_period])) * 100 \n/ \nsum by (method)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "method: {{method}}"
    }
   ]
  },
  {
   "title": "Fallback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocations triggering Fallback [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of method invocations which resulted in the fallback method or handler being called over the past $avg_period.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, fallback='applied'}[$avg_period])) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Invocations triggering Fallback averaged over $instance instance(s) [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of method invocations which resulted in the fallback method or handler being called over the past $avg_period.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_invocations_total{instance=~`${instance}`, fallback='applied'}[$avg_period])) * 100 \n/ \nsum by (method)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Invocations failed after Fallback [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of method invocations which failed once the Fallback method or handler had been called",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, fallback='applied',result='exceptionThrown'}[$avg_period])) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, fallback='applied'}[$avg_period]))",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Invocations failed after Fallback averaged over $instance instance(s) [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of method invocations which failed once the Fallback method or handler had been called",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_invocations_total{fallback='applied',result='exceptionThrown'}[$avg_period])) * 100 \n/ \nsum by (method)(rate(base_ft_invocations_total{fallback='applied'}[$avg_period]))",
       "legendFormat": "method: {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Retry Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocations failed despite retries [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of method invocation which failed, despite retrying, over the last $avg_period.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum without (retryResult, retried)(rate(base_ft_retry_calls_total{instance=~`${instance}`, retried='true', retryResult!='valueReturned'}[$avg_period])*100)\n/\nsum without (retryResult, retried)(rate(base_ft_retry_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Invocations failed despite retries averaged over $instance instance(s) [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of method invocation which failed, despite retrying, over the last $avg_period.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_retry_calls_total{instance=~`${instance}`, retried='true', retryResult!='valueReturned'}[$avg_period])*100)\n/\nsum by (method)(rate(base_ft_retry_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Retries per invocation [avg $avg_period]",
     "type": "graph",
     "description": "Average number of retries which occurred for each method invocation.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Retries per invocation" }
     ],
     "targets": [
      {
       "expr": "sum without()(rate(base_ft_retry_retries_total{instance=~`${instance}`}[$avg_period]))\n/\nsum without (retried, retryResult)(rate(base_ft_retry_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Retries per invocation averaged over $instance instance(s) [avg $avg_period]",
     "type": "graph",
     "description": "Average number of retries which occurred for each method invocation.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Retries per invocation" }
     ],
     "targets": [
      {
       "expr": "sum by(method)(rate(base_ft_retry_retries_total{instance=~`${instance}`}[$avg_period]))\n/\nsum by(method)(rate(base_ft_retry_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "method: {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Timeout Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocations timed out [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of invocations which timed out",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum without (timedOut)(rate(base_ft_timeout_calls_total{instance=~`${instance}`, timedOut='true'}[$avg_period])) * 100\n/\nsum without (timedOut)(rate(base_ft_timeout_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Invocations timed out averaged over $instance instance(s) [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of invocations which timed out",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_timeout_calls_total{instance=~`${instance}`, timedOut='true'}[$avg_period])) * 100\n/\nsum by (method)(rate(base_ft_timeout_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Execution duration $quantile quantile for methods with a Timeout [s, avg 1000 exec.]",
     "type": "graph",
     "description": "Shows the selected quantile of execution times using a weighted average of the last 1000 executions.\n\nThe quantiles should be understood like this: if the 0.99 quantile is 300ms, then 99% of executions took less than 300ms. (Conversely, 1% of executions took longer than 300ms)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "base_ft_timeout_executionDuration_seconds{instance=~`${instance}`, quantile=`${quantile}`}",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Execution duration mean for methods with a Timeout [s, avg 1000 exec.]",
     "type": "graph",
     "description": "The average duration a method with a Timeout executes for to return a value, using a weighted average of the last 1000 executions.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "base_ft_timeout_executionDuration_mean_seconds{instance=~`${instance}`}",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bulkhead Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocations rejected by Bulkhead [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of calls which were rejected because the bulkhead was full over the last $avg_period.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum without (bulkheadResult)(rate(base_ft_bulkhead_calls_total{instance=~`${instance}`, bulkheadResult='rejected'}[$avg_period])*100)\n/\nsum without (bulkheadResult)(rate(base_ft_bulkhead_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Invocations rejected by Bulkhead averaged over $instance instance(s) [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of calls which were rejected because the bulkhead was full over the last $avg_period.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_bulkhead_calls_total{instance=~`${instance}`, bulkheadResult='rejected'}[$avg_period])*100)\n/\nsum by (method)(rate(base_ft_bulkhead_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Execution duration $quantile quantile for methods with a Bulkhead [s, avg 1000 exec.]",
     "type": "graph",
     "description": "Shows the selected quantile of execution times, for methods running with a Bulkhead, using a weighted average of the last 1000 executions.\n\nThe quantiles should be understood like this: if the 0.99 quantile is 300ms, then 99% of executions took less than 300ms. (Conversely, 1% of executions took longer than 300ms)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "base_ft_bulkhead_runningDuration_seconds{instance=~`${instance}`, quantile=`${quantile}`}",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Execution duration mean for methods with a Bulkhead [s, avg 1000 exec.]",
     "type": "graph",
     "description": "The average duration a method with a Bulkhead runs for to return a value, using a weighted average of the last 1000 executions.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "base_ft_bulkhead_runningDuration_mean_seconds{instance=~`${instance}`}",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Estimated number of attempted concurrent calls through a Bulkhead [avg 1m]",
     "type": "graph",
     "description": "Estimate of the number of concurrent calls that are attempted through the bulkhead.\n\nThis is done by multiplying the number of attempted invocations by the mean execution time.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Concurrent attempts" }
     ],
     "targets": [
      {
       "expr": "sum without (bulkheadResult)(rate(base_ft_bulkhead_calls_total{instance=~`${instance}`}[30s]))\n*\nbase_ft_bulkhead_runningDuration_mean_seconds{instance=~`${instance}`}",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit Breaker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Invocations rejected by Circuit Breaker [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of calls which were rejected because the Circuit Breaker was open over the last $avg_period.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum without (circuitBreakerResult)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult='circuitBreakerOpen'}[$avg_period])*100)\n/\nsum without (circuitBreakerResult)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`}[$avg_period]))",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Invocations rejected by Circuit Breaker averaged over $instance instance(s) [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of calls which were rejected because the bulkhead was open over the last $avg_period.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`,circuitBreakerResult='circuitBreakerOpen'}[$avg_period])*100)\n/\nsum by (method)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`,}[$avg_period]))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Circuit Breaker run but failed [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of invocations which were permitted to run by the circuit breaker but failed.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "repeat": "method",
     "yaxes": [
      { "format": "percent", "label": "Failure %" }
     ],
     "targets": [
      {
       "expr": "sum without (circuitBreakerResult)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult='failure'}[$avg_period]))*100\n/\nsum without (circuitBreakerResult)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult=~'success|failure'}[$avg_period]))",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Circuit Breaker run but failed averaged over $instance instance(s) [%, avg $avg_period]",
     "type": "graph",
     "description": "Percentage of invocations which were permitted to run by the circuit breaker but failed.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "percent", "label": "Failure %" }
     ],
     "targets": [
      {
       "expr": "sum by (method)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult='failure'}[$avg_period]))*100\n/\nsum by (method)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult=~'success|failure'}[$avg_period]))",
       "legendFormat": "method: {{method}}"
      }
     ]
    },
    {
     "title": "Circuit Breaker not closed [%]",
     "type": "graph",
     "description": "Shows the percentage of time per-second that the Circuit Breaker spends in an Open or Half Open state.\n\nThe graph checks back for up to 1 minute for the two most recent data points.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      {
       "format": "percent",
       "label": "Percentage of time not closed per second"
      }
     ],
     "targets": [
      {
       "expr": "sum without (state)(irate(base_ft_circuitbreaker_state_total_seconds{instance=~`${instance}`, state!='closed'}[1m])*100)",
       "legendFormat": "instance: {{instance}}, method: {{method}}"
      }
     ]
    }
   ]
  }
 ]
}